### ISSUE TITLE
驱动后是否有卡顿现象？

### ISSUE THREAD

**Issue by Odinysus** [Matchas-xiaobin/EFI-B360m_d2v_OpenCore_dvi_uhd630#1]
MSI 360M + CPU 8700
显示已经驱动了，但是进入工作台的时候很卡

**Comment by Matcha-xiaobin** [comment]
不太清楚你的为什么会卡顿，目前我一直稳定流畅使用了很长时间，没有异常。
如果是拖动窗口或者过渡动画掉帧的话，建议自行定制下缓冲帧试试。
