### ISSUE TITLE
大佬，用的您的EFI其他都很顺利，现在只有一个问题：每次开机进系统大概都要重启3-4次，请问这个怎么解决呢？

### ISSUE THREAD

**Issue by Jingle-Li** [Matchas-xiaobin/EFI-B360m_d2v_OpenCore_dvi_uhd630#2]

**Comment by Matcha-xiaobin** [comment]
很抱歉，由于我没遇到过这情况，无法帮到你。
另外，由于我很久没折腾黑果了，所以OC版本也好几个版本没更新了，建议自行参照OC的文档更新下最新的版本尝试下。

**Comment by Jingle-Li** [comment]
> 很抱歉，由于我没遇到过这情况，无法帮到你。
> 另外，由于我很久没折腾黑果了，所以OC版本也好几个版本没更新了，建议自行参照OC的文档更新下最新的版本尝试下。

感谢！
